SELECT 
    TENURE,
    AVG(TOTAL_SALES_AMOUNT) AS AVG_TOTAL_SALES_AMOUNT,
    AVG(PERFORMANCE_RATING) AS AVG_PERFORMANCE_RATING,
    AVG(ORDERS_PROCESSED) AS AVG_ORDERS_PROCESSED
FROM {{ ref('dim_employee') }}
GROUP BY TENURE