WITH CTE_TOP_EMP AS(
    SELECT 
        REGION,
        EMPLOYEE_ID,
        DENSE_RANK() OVER(PARTITION BY REGION ORDER BY TOTAL_SALES_AMOUNT DESC) AS RANK
    FROM {{ ref('dim_employee') }} AS E
    LEFT JOIN {{ ref('dim_store') }} AS S
        ON E.WORK_LOCATION = S.STORE_ID
)
SELECT REGION,
    EMPLOYEE_ID,
    RANK
FROM CTE_TOP_EMP
WHERE RANK <= 5