
WITH CTE_CUST_DETAILS AS (
    SELECT 
        CUSTOMER_KEY,
        MIN(ORDER_DATE) AS FIRST_ORDER_DATE,
        MAX(ORDER_DATE) AS LAST_ORDER_DATE,
        COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT,
        SUM(TOTAL_SALES_AMOUNT) AS TOTAL_AMOUNT,
        COUNT(DISTINCT CASE
            WHEN SALES_CHANNEL = 'Online'
            THEN ORDER_ID END) AS ONLINE_ORDERS,
        COUNT(DISTINCT CASE
            WHEN SALES_CHANNEL = 'In-Store'
            THEN ORDER_ID END) AS OFFINE_ORDERS        
    FROM {{ ref('fact_sales') }} 
    GROUP BY CUSTOMER_KEY
)
SELECT 
    CUSTOMER_ID,
    FULL_NAME,
    CAST(FIRST_ORDER_DATE AS DATE) AS FIRST_ORDER_DATE,
    CAST(LAST_ORDER_DATE AS DATE) AS LAST_ORDER_DATE,
    ORDER_COUNT,
    OFFINE_ORDERS,
    ONLINE_ORDERS,
    TOTAL_AMOUNT
FROM CTE_CUST_DETAILS CD 
RIGHT JOIN {{ ref('dim_customers') }} C
    ON CD.CUSTOMER_KEY = C.CUSTOMER_KEY
