SELECT 
    SUBCATEGORY,
    SUM(TOTAL_SALES_AMOUNT) AS TOTAL_SALES_AMOUNT
FROM {{ ref('fact_sales') }} F
LEFT JOIN {{ ref('dim_product') }} P
    ON F.PRODUCT_KEY = P.PRODUCT_KEY
GROUP BY SUBCATEGORY
