WITH product AS (
    SELECT * FROM {{ ref('snp_product_data') }}
)
SELECT 
    TRIM(PRODUCT_ID) AS PRODUCT_ID,
    REPLACE(INITCAP(TRIM(PRODUCT_NAME)),' ','') AS PRODUCT_NAME,
    INITCAP(TRIM(BRAND)) AS BRAND,
    TRIM(SUPPLIER_ID) AS SUPPLIER_ID,
    REPLACE(INITCAP(TRIM(CATEGORY)),' ','') AS CATEGORY,
    INITCAP(TRIM(SUBCATEGORY)) AS SUBCATEGORY,
    INITCAP(TRIM(PRODUCT_LINE)) AS PRODUCT_LINE,
    INITCAP(TRIM(CATEGORY)) || ' > ' || INITCAP(TRIM(SUBCATEGORY)) || ' > ' || INITCAP(TRIM(PRODUCT_LINE)) AS PRODUCT_HEIRARCHY,
    INITCAP(TRIM(SHORT_DESCRIPTION)) AS SHORT_DESCRIPTION,
    INITCAP(TRIM(TECHNICAL_SPECS)) AS TECHNICAL_SPECS,
    INITCAP(TRIM(PRODUCT_NAME)) || ' - ' || INITCAP(TRIM(SHORT_DESCRIPTION)) || ' - ' || INITCAP(TRIM(TECHNICAL_SPECS)) AS FULL_DESCRIPTION,
    INITCAP(TRIM(COLOR)) AS COLOR,
    INITCAP(TRIM(SIZE)) AS SIZE,
    UPPER(TRIM(WEIGHT)) AS WEIGHT,
    UPPER(TRIM(DIMENSIONS)) AS DIMENSIONS,
    INITCAP(TRIM(WARRANTY_PERIOD)) AS WARRANTY_PERIOD,
    UNIT_PRICE,
    COST_PRICE,
    STOCK_QUANTITY,
    REORDER_LEVEL,
    ((UNIT_PRICE-COST_PRICE)/UNIT_PRICE)*100.0 AS PROFIT_MARGIN_PERCENTAGE,
    CASE 
        WHEN STOCK_QUANTITY < REORDER_LEVEL THEN TRUE
        ELSE FALSE
    END AS LOW_STOCK,
    IS_FEATURED,
    LAUNCH_DATE,
    LAST_MODIFIED_DATE
FROM product
WHERE DBT_VALID_TO IS NULL