WITH orders AS (
    SELECT * FROM {{ ref('flatened_orders_data') }}
), 
CTE_ORDER_ITEMS_COMBINED AS (
    SELECT 
        ORDER_ID,
        SUM(QUANTITY*COST_PRICE) AS TOTAL_COST_PRICE,
        COUNT(PRODUCT_ID) AS TOTAL_ITEMS,
        SUM(QUANTITY) AS TOTAL_QUANTITY,
        SUM(QUANTITY*UNIT_PRICE) AS TOTAL_UNIT_PRICE
    FROM {{ ref('flatened_order_items_data') }}
    GROUP BY ORDER_ID
),
CTE_ORDER_AND_ORDER_ITEMS AS (
    SELECT 
        O.*,
        OI.TOTAL_COST_PRICE,
        OI.TOTAL_ITEMS,
        OI.TOTAL_QUANTITY,
        OI.TOTAL_UNIT_PRICE
    FROM orders O
    JOIN CTE_ORDER_ITEMS_COMBINED OI 
        ON O.ORDER_ID = OI.ORDER_ID
)
SELECT 
    TRIM(ORDER_ID) AS ORDER_ID,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    TRIM(STORE_ID) AS STORE_ID,
    TRIM(EMPLOYEE_ID) AS EMPLOYEE_ID,
    TRIM(CAMPAIGN_ID) AS CAMPAIGN_ID,
    UPPER(TRIM(ORDER_STATUS)) AS ORDER_STATUS,
    INITCAP(TRIM(ORDER_SOURCE)) AS ORDER_SOURCE,
    INITCAP(TRIM(PAYMENT_METHOD)) AS PAYMENT_METHOD,
    INITCAP(TRIM(SHIPPING_METHOD)) AS SHIPPING_METHOD,
    TOTAL_AMOUNT,
    (((TOTAL_AMOUNT-TOTAL_COST_PRICE + TOTAL_DISCOUNT - SHIPPING_COST -TAX_AMOUNT))*(100.0))/TOTAL_AMOUNT AS PROFIT_MARGIN_PER,
    TOTAL_ITEMS,
    TOTAL_QUANTITY,
    TOTAL_UNIT_PRICE,
    TOTAL_COST_PRICE,
    TOTAL_DISCOUNT,
    SHIPPING_COST,
    TAX_AMOUNT,
    ORDER_DATE,
    WEEK(ORDER_DATE) AS ORDER_WEEK,
    MONTH(ORDER_DATE) AS ORDER_MONTH,
    QUARTER(ORDER_DATE) AS ORDER_QUATER,
    YEAR(ORDER_DATE) AS ORDER_YEAR,
    CASE 
        WHEN HOUR(TO_TIME(ORDER_DATE)) >= 5 AND HOUR(TO_TIME(ORDER_DATE)) < 12 THEN 'Morning'
        WHEN HOUR(TO_TIME(ORDER_DATE)) >= 12 AND HOUR(TO_TIME(ORDER_DATE)) < 17 THEN 'Afternoon'
        WHEN HOUR(TO_TIME(ORDER_DATE)) >= 17 AND HOUR(TO_TIME(ORDER_DATE)) < 22 THEN 'Evening'
    ELSE 'Night'
    END AS ORDER_TIME,
    CREATED_AT,
    SHIPPING_DATE,
    DATEDIFF(DAY,ORDER_DATE,SHIPPING_DATE) AS PROCESSING_DAYS,
    DATEDIFF(DAY,SHIPPING_DATE,DELIVERY_DATE) AS SHIPPING_DAYS,
    CASE 
        WHEN DELIVERY_DATE IS NOT NULL AND DELIVERY_DATE <= ESTIMATED_DELIVERY_DATE THEN 'On-Time'
        WHEN DELIVERY_DATE IS NOT NULL AND DELIVERY_DATE > ESTIMATED_DELIVERY_DATE THEN 'Delayed'
        WHEN DELIVERY_DATE IS NULL AND CURRENT_DATE() > ESTIMATED_DELIVERY_DATE THEN 'Potentially Delayed'
    ELSE 'In Transit'
    END AS DELIVERY_STATUS,
    DELIVERY_DATE,
    ESTIMATED_DELIVERY_DATE,
    INITCAP(TRIM(SHIPPING_STREET)) AS SHIPPING_STREET,
    INITCAP(TRIM(SHIPPING_CITY)) AS SHIPPING_CITY,
    UPPER(TRIM(SHIPPING_STATE)) AS SHIPPING_STATE,	
    TRIM(SHIPPING_ZIP) AS SHIPPING_ZIP,
    INITCAP(TRIM(BILLING_STREET)) AS BILLING_STREET,
    INITCAP(TRIM(BILLING_CITY)) AS BILLING_CITY,
    UPPER(TRIM(BILLING_STATE)) AS BILLING_STATE,
    TRIM(BILLING_ZIP) AS BILLING_ZIP
FROM CTE_ORDER_AND_ORDER_ITEMS