WITH order_items AS (
    SELECT * FROM {{ ref('flatened_order_items_data') }}
)
SELECT 
    ORDER_ID,
    MAX(COST_PRICE) AS COST_PRICE,
    MAX(DISCOINT_AMOUNT) AS DISCOINT_AMOUNT,
    PRODUCT_ID,
    SUM(QUANTITY) AS QUANTITY,
    MAX(UNIT_PRICE) AS UNIT_PRICE
FROM order_items
GROUP BY ORDER_ID, PRODUCT_ID