WITH store AS (
    SELECT * FROM {{ ref('snp_store_data') }}
)
SELECT 
    TRIM(STORE_ID) AS STORE_ID,
    REPLACE(INITCAP(TRIM(STORE_NAME)),' ','') AS STORE_NAME,
    INITCAP(TRIM(REGION)) AS REGION,
    INITCAP(TRIM(STORE_TYPE)) AS STORE_TYPE,	
    TRIM(MANAGER_ID) AS MANAGER_ID,
    REGEXP_REPLACE(TRIM(PHONE_NUMBER),'[^0-9]','') AS PHONE_NUMBER,
    TRIM(EMAIL) AS EMAIL,
    INITCAP(TRIM(STREET)) AS STREET,
    INITCAP(TRIM(CITY)) AS CITY,	
    TRIM(ZIP_CODE) AS ZIP_CODE,
    UPPER(TRIM(COUNTRY)) AS COUNTRY,
    TRIM(HOURS_WEEKDAYS) AS HOURS_WEEKDAYS,	
    TRIM(HOURS_WEEKENDS) AS HOURS_WEEKENDS,
    TRIM(HOURS_HOLIDAYS) AS HOURS_HOLIDAYS,
    SIZE_SQ_FT,
    CASE 
        WHEN SIZE_SQ_FT<5000 THEN 'Small'
        WHEN SIZE_SQ_FT>=5000 AND SIZE_SQ_FT<=10000  THEN 'Medium'
        WHEN SIZE_SQ_FT>10000 THEN 'Large'
    END AS SIZE_CATEGORY,
    EMPLOYEE_COUNT,
    MONTHLY_RENT,
    SALES_TARGET,
    CURRENT_SALES,
    (CURRENT_SALES*100.0/SALES_TARGET) AS SALE_TAGET_ACHEIVE_PER,
    (CURRENT_SALES/SIZE_SQ_FT) AS REVENUE_PER_SQ_FT,
    (CURRENT_SALES/EMPLOYEE_COUNT) AS EMPLOYEE_EFFICIENCY,
    IS_ACTIVE,
    OPENING_DATE,
    DATEDIFF(YEAR,OPENING_DATE,CURRENT_DATE()) AS STORE_AGE,
    CASE   
        WHEN (CURRENT_SALES*100.0/SALES_TARGET) < 90 THEN TRUE
        ELSE FALSE
    END AS PERFORMANCE_ISSUES,
    LAST_MODIFIED_DATE,
    SERVICES
FROM store
WHERE DBT_VALID_TO IS NULL