WITH supplier AS (
    SELECT * FROM {{ ref('snp_suppliers_data') }}
)
SELECT 
    TRIM(SUPPLIER_ID) AS SUPPLIER_ID,
    INITCAP(TRIM(SUPPLIER_NAME)) AS SUPPLIER_NAME,
    INITCAP(TRIM(SUPPLIER_TYPE)) AS SUPPLIER_TYPE,
    UPPER(TRIM(PAYMENT_TERMS)) AS PAYMENT_TERMS,
    UPPER(TRIM(CREDIT_RATING)) AS CREDIT_RATING,
    UPPER(TRIM(TAX_ID)) AS TAX_ID,
    TRIM(WEBSITE) AS WEBSITE,
    INITCAP(TRIM(CONTACT_PERSON)) AS CONTACT_PERSON,
    TRIM(CONTACT_EMAIL) AS CONTACT_EMAIL,
    REGEXP_REPLACE(TRIM(TRIM(CONTACT_PHONE)),'[^0-9]','') AS CONTACT_PHONE,
    INITCAP(TRIM(FULL_ADDRESS)) AS FULL_ADDRESS,
    UPPER(TRIM(CONTRACT_ID)) AS CONTRACT_ID,
    CONTRACT_START_DATE,
    CONTRACT_END_DATE,
    RENEWAL_OPTION,
    EXCLUSIVITY,
    ON_TIME_DELIVERY_RATE,
    AVG_DELAY_DAYS,
    DEFECT_RATE,
    RETURNS_PCT,
    INITCAP(TRIM(QUALITY_RATING)) AS QUALITY_RATING,
    RESPONSE_TIME_HOURS,
    LEAD_TIME_DAYS,
    MINIMUM_ORDER_QUANTITY,
    UPPER(TRIM(PREFERRED_CARRIER)) AS PREFERRED_CARRIER,
    YEAR_ESTABLISHED,
    IS_ACTIVE,
    LAST_ORDER_DATE,
    LAST_MODIFIED_DATE,
    CATEGORIES_SUPPLIED
FROM supplier
WHERE DBT_VALID_TO IS NULL