WITH employee AS (
    SELECT * FROM {{ ref('snp_employee_data') }}
)
SELECT 
    TRIM(EMPLOYEE_ID) AS EMPLOYEE_ID,
    INITCAP(TRIM(FIRST_NAME)) AS FIRST_NAME,
    INITCAP(TRIM(LAST_NAME)) AS LAST_NAME,
    INITCAP(TRIM(FIRST_NAME)) || ' ' ||  INITCAP(TRIM(LAST_NAME)) AS FULL_NAME,
    TRIM(EMAIL) AS EMAIL,
    REGEXP_REPLACE(TRIM(PHONE),'[^0-9]','') AS PHONE,
    CASE 
        WHEN INITCAP(TRIM(ROLE)) = 'Sales Associate' THEN 'Associate'
        WHEN INITCAP(TRIM(ROLE)) = 'Store Manager' THEN 'Manager'
    ELSE INITCAP(TRIM(ROLE))
    END AS ROLE,
    INITCAP(TRIM(DEPARTMENT)) AS DEPARTMENT,
    TRIM(WORK_LOCATION) AS WORK_LOCATION,
    TRIM(MANAGER_ID) AS MANAGER_ID,
    UPPER(TRIM(EMPLOYMENT_STATUS)) AS EMPLOYMENT_STATUS,
    INITCAP(TRIM(EDUCATION)) AS EDUCATION,
    HIRE_DATE,
    DATEDIFF(YEAR,HIRE_DATE,CURRENT_DATE()) AS TENURE,
    DATE_OF_BIRTH,
    LAST_MODIFIED_DATE,
    SALARY,
    SALES_TARGET,
    CURRENT_SALES,
    (CURRENT_SALES*100.0/SALES_TARGET) AS TARGET_ACHEIVE_PER,
    PERFORMANCE_RATING,
    INITCAP(TRIM(STREET)) AS STREET,
    INITCAP(TRIM(CITY)) AS CITY,
    UPPER(TRIM(STATE)) AS STATE,
    TRIM(ZIP_CODE) AS ZIP_CODE,
    CERTIFICATIONS
FROM employee
WHERE DBT_VALID_TO IS NULL