WITH campaign AS (
    SELECT * FROM {{ ref('snp_campaign_data') }}
)
SELECT 
    TRIM(CAMPAIGN_ID) AS CAMPAIGN_ID,
    TRIM(CAMPAIGN_NAME) AS CAMPAIGN_NAME,
    TRIM(CAMPAIGN_TYPE) AS CAMPAIGN_TYPE,
    START_DATE,
    END_DATE,
    DATEDIFF(DAY,CAST(START_DATE AS DATE),CAST(END_DATE AS DATE)) AS CAMPAIGN_DURATION,
    LAST_MODIFIED_DATE,
    CAST(REPLACE(REPLACE(BUDGET,'$',''),',','') AS FLOAT) AS BUDGET,
    CAST(REPLACE(REPLACE(TOTAL_COST,'$',''),',','') AS FLOAT) AS TOTAL_COST,
    CAST(REPLACE(REPLACE(TOTAL_REVENUE,'$',''),',','') AS FLOAT) AS TOTAL_REVENUE,
    CAST(
    (
        CAST(REPLACE(REPLACE(TOTAL_REVENUE,'$',''),',','') AS FLOAT)
        -
        CAST(REPLACE(REPLACE(TOTAL_COST,'$',''),',','') AS FLOAT)
    )/
        CAST(REPLACE(REPLACE(TOTAL_COST,'$',''),',','') AS FLOAT) 
        AS NUMERIC(10,2))AS EXPECTED_ROI,
    ROI_CALCULATION,
    TARGET_AUDIENCE,
    TRIM(CHANNEL) AS CHANNEL,
    TRIM(DESCRIPTION) AS DESCRIPTION
FROM campaign
WHERE DBT_VALID_TO IS NULL