WITH customer AS (
    SELECT * FROM {{ ref('snp_customers_data') }}
)
SELECT 
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    INITCAP(TRIM(FIRST_NAME)) AS FIRST_NAME,
    INITCAP(TRIM(LAST_NAME)) AS LAST_NAME,
    INITCAP(TRIM(FIRST_NAME)) ||  ' ' || INITCAP(TRIM(LAST_NAME)) AS FULL_NAME,
    TRIM(EMAIL) AS EMAIL,
    REGEXP_REPLACE(TRIM(PHONE),'[^0-9]','') AS PHONE,
    TRIM(BIRTH_DATE) AS BIRTH_DATE,
    YEAR(CURRENT_DATE()) - CAST(REGEXP_SUBSTR(TRIM(BIRTH_DATE),'\\d{4}') AS INT) AS AGE,
    CASE 
        WHEN AGE >= 18 AND AGE <= 35 THEN 'Young'
        WHEN AGE >= 36 AND AGE <= 55 THEN 'Middle-aged'
        WHEN AGE > 55  THEN 'Senior'
    ELSE 'Unknown'
    END AS CUSTOMER_SEGMENT,
    INITCAP(TRIM(STREET)) AS STREET,
    INITCAP(TRIM(CITY)) AS CITY,
    UPPER(TRIM(STATE)) AS STATE,
    TRIM(ZIP_CODE) AS ZIP_CODE,
    UPPER(TRIM(COUNTRY)) AS COUNTRY,
    REGISTRATION_DATE,
    UPPER(TRIM(PREFERRED_COMMUNICATION)) AS PREFERRED_COMMUNICATION,
    INITCAP(TRIM(OCCUPATION)) AS OCCUPATION,
    INITCAP(TRIM(INCOME_BRACKET)) AS INCOME_BRACKET,
    INITCAP(TRIM(LOYALTY_TIER)) AS LOYALTY_TIER,
    TOTAL_PURCHASES,
    TOTAL_SPEND,
    INITCAP(TRIM(PREFERRED_PAYMENT_METHOD)) AS PREFERRED_PAYMENT_METHOD,
    MARKETING_OPT_IN,
    LAST_PURCHASE_DATE,
    LAST_MODIFIED_DATE,
FROM customer
WHERE DBT_VALID_TO IS NULL