WITH CTE_ORDER_COUNT AS (
SELECT 
    CUSTOMER_KEY,
    COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT,
    SUM(TOTAL_SALES_AMOUNT) AS TOTAL_SALES_AMOUNT,
FROM {{ ref('fact_sales') }}
GROUP BY CUSTOMER_KEY
)
SELECT 
    CUSTOMER_SEGMENT,
    COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS,
    SUM(ORDER_COUNT) AS ORDER_COUNT,
    SUM(TOTAL_SALES_AMOUNT) AS TOTAL_SALES_AMOUNT
FROM CTE_ORDER_COUNT O
RIGHT JOIN {{ ref('dim_customers') }} C
    ON C.CUSTOMER_KEY = O.CUSTOMER_KEY
GROUP BY CUSTOMER_SEGMENT
