WITH CTE_CUST_LIFE_VALUE AS (
    SELECT 
        FS.CUSTOMER_KEY,
        SUM(TOTAL_SALES_AMOUNT) AS TOTAL_SALES_AMOUNT
    FROM {{ ref('fact_sales') }} FS 
    GROUP BY FS.CUSTOMER_KEY
)
SELECT 
    CUSTOMER_ID,
    FULL_NAME,
    TOTAL_SALES_AMOUNT
FROM CTE_CUST_LIFE_VALUE CV
RIGHT JOIN {{ ref('dim_customers') }} C
    ON C.CUSTOMER_KEY = CV.CUSTOMER_KEY