WITH CTE_ORDER_COUNT AS (
SELECT 
    CUSTOMER_KEY,
    COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT
FROM {{ ref('fact_sales') }}
GROUP BY CUSTOMER_KEY
)
SELECT 
    CUSTOMER_ID,
    FULL_NAME,
    ORDER_COUNT
FROM CTE_ORDER_COUNT O
RIGHT JOIN {{ ref('dim_customers') }} C
    ON C.CUSTOMER_KEY = O.CUSTOMER_KEY